### PR TITLE
add type definition

### PR DESCRIPTION
**Pull request by taoqf**
see https://github.com/mochixuan/react-native-smart-tip/pull/4

### CODE REVIEW

**Comment by taoqf** [comment]
All issues fixed in this pr. 
Add all tests in readme, tested and passed.
This is the correct write style of type definition.

**Comment by taoqf** [comment]
@mochixuan

**Comment by mochixuan** [comment]
Thank you for your submission, x.d.ts is just a statement and prompt, some of the parameters are indeed enum better than static, but the current statement is already available.

**Comment by taoqf** [comment]
You are the boss.

**Pull request closed without merging**
