### PR TITLE
useNativeDriver

### PR DESCRIPTION
**Pull request by taoqf**
Without this flag, it runs really slow on android.

### CODE REVIEW

**Comment by mochixuan** [comment]
useNativeDriver allows the animation to be rendered natively, reducing the generation of virtual doms and the comparison of diff algorithms, but will cause the js side to lose control of the animation, but it can be added here. useNativeDriver is a very nice optimized pair of animations.

**Comment by taoqf** [comment]
Learned.
Do you mean we don't need `useNativeDriver`?
Then why don't we add it since we don't need to cancel the animation?

**Comment by mochixuan** [comment]
In normal development, useNativeDriver is generally added, which can reduce the virtual DOM generation and Diff comparison on the React side during the animation process. The animation process is all given to the original, and the RN gives up management rights.

**Comment by taoqf** [comment]
Um, do you mean you won't merge this pr?

**Pull request closed without merging**
